const image =
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80";
const rows = [
  [
    "1",
    "sriracha-bay-residence",
    "Sriracha Bay Residence",
    "Sriracha",
    2850000,
    2,
    2,
    68,
    "CONDO",
  ],
  [
    "2",
    "harbor-view-condo",
    "Harbor View Condo",
    "Laem Chabang",
    1950000,
    1,
    1,
    42,
    "CONDO",
  ],
  [
    "3",
    "ocean-park-living",
    "Ocean Park Living",
    "Bangsaen",
    4200000,
    3,
    2,
    124,
    "HOUSE",
  ],
  [
    "4",
    "eastern-living-residence",
    "Eastern Living Residence",
    "Pattaya",
    3450000,
    2,
    2,
    76,
    "CONDO",
  ],
  [
    "5",
    "pacific-heights-sriracha",
    "Pacific Heights Sriracha",
    "Sriracha",
    5900000,
    3,
    3,
    182,
    "HOUSE",
  ],
  [
    "6",
    "coral-cove-villa",
    "Coral Cove Villa",
    "Pattaya",
    7800000,
    4,
    4,
    260,
    "VILLA",
  ],
  [
    "7",
    "burapha-garden-home",
    "Burapha Garden Home",
    "Bangsaen",
    3150000,
    3,
    2,
    140,
    "HOUSE",
  ],
  [
    "8",
    "marina-link-townhome",
    "Marina Link Townhome",
    "Laem Chabang",
    2390000,
    3,
    2,
    110,
    "TOWNHOME",
  ],
  [
    "9",
    "azure-coast-condo",
    "Azure Coast Condo",
    "Pattaya",
    1650000,
    1,
    1,
    35,
    "CONDO",
  ],
  [
    "10",
    "casaluna-green",
    "Casaluna Green",
    "Bangsaen",
    4850000,
    3,
    3,
    168,
    "HOUSE",
  ],
  [
    "11",
    "portside-place",
    "Portside Place",
    "Laem Chabang",
    2750000,
    2,
    2,
    64,
    "CONDO",
  ],
  [
    "12",
    "serene-hills-sriracha",
    "Serene Hills Sriracha",
    "Sriracha",
    6500000,
    4,
    3,
    220,
    "VILLA",
  ],
] as const;
export const properties = rows.map((r, i) => ({
  id: r[0],
  slug: r[1],
  title: r[2],
  location: r[3],
  price: r[4],
  bedrooms: r[5],
  bathrooms: r[6],
  areaSqm: r[7],
  propertyType: r[8],
  province: "Chonburi",
  status: "AVAILABLE",
  featured: i < 4,
  description: `A thoughtfully designed fictional home in ${r[3]}, Chonburi.`,
  amenities: [
    "24-hour security",
    "Fitness room",
    "Green space",
    "Covered parking",
  ],
  images: [image],
}));
